### ISSUE TITLE
El alumno puede crear clases

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#10]
Hola, 

¿Tiene sentido que los alumnos puedan crear clases?

Un saludo, 
![Alumno](https://user-images.githubusercontent.com/4247635/96373816-2a151980-116f-11eb-8097-a42a2dfbe1b2.png)

**Comment by climentjoan** [comment]
Un usuario es un usuario, y si un alumno se registra como docente puede crear nuevas clases.

Si al alumno lo da de alta un docente, por defecto es estudiante y no puede crear clases, pero siempre podrá activarlo en el perfil, ya que no tiene sentido no permitir crear clases a un usuario porque alguien lo haya dado de alta en la plataforma.
