### ISSUE TITLE
Edición líneas de evaluación

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#12]
Hola, 

Estaría bien la posibilidad de poder editar las líneas de evaluación.

Un saludo,

**Comment by climentjoan** [comment]
Sí, es una función que está prevista para un futuro.

¡Un saludo!

**Comment by oscarflofer** [comment]
Hola buenas, estoy teniendo problemas en los iconos ya que no aparecen y en su lugar hay un espacio en blanco o como mini cuadrados de colores donde si paso el cursor por encima y clickeo si funcionan, pero claro, no sé lo que estoy clickeando hasta que no lo hago (no se ve el icono)...a qué puede deberse?

**Comment by climentjoan** [comment]
Hola @oscarflofer, parece que estás bloqueando "Font Awesome". ¿Podrías probar en modo incógnito o en otro navegador?

**Comment by oscarflofer** [comment]
Igual, en modo incógnito tampoco me salen

**Comment by oscarflofer** [comment]
Pero también me aparece así en el móvil y en la Tablet...

**Comment by climentjoan** [comment]
No me explico por qué 🤔 si puedes pásate por el Telegram y ábreme privado, será más fácil de encontrar el problema

**Comment by oscarflofer** [comment]
Cuál es el enlace a telegram? pásamelo y te puedo enviar pantallazo de por qué me sale eso

**Comment by oscarflofer** [comment]
Acabo de ponerlo por Telegram

**Comment by climentjoan** [comment]
Ya está solucionado, y ya se pueden editar las líneas de evaluación, cierro 😄
