### ISSUE TITLE
Propuesta Evaluación

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#13]
Hola, 

Me gustaría saber la posibilidad de poder modificar el apartado de evaluación, en visión alumnos, ya que, para los que tenemos más de una asignatura con el alumnado, no lo vemos muy viable, al menos los de mi centro.

La idea sería dividir la lista de evaluación como intentamos mostrar en la imagen adjunta, si es posible. Con esto conseguimos que el alumnado pueda ver su nota dividida por categoría = materia. Para ello, habría que asociar las etiquetas a las categorías, previamente creadas, y mostrar tantas listas como categorías tengas, y tantas etiquetas por cada lista, como se hayan asociado a esa categoría. 

![Evaluacion](https://user-images.githubusercontent.com/4247635/96374209-8ed17380-1171-11eb-9f4b-e2e0bbffa862.png)

Un saludo,

**Comment by climentjoan** [comment]
Esta mejora y está disponible. Cierro :smile:
