### ISSUE TITLE
Monstruos - Literal

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#22]
En el PopUp de creación de monstruos, en la lengua castellana, el placeholder aparece el texto "Careful cat".

**Comment by climentjoan** [comment]
Es un ejemplo de nombre de monstruo, no veo la necesidad de traducirlo. Es como los nombres aleatorios de grupos, lo que puedo hacer es que aparezcan aleatorios para dar ideas de nombres.
