### ISSUE TITLE
Monstruos - Advertencia al empezar

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#23]
Cuando estás haciendo el paso a paso para lanzar una batalla contra un monstruo, si no seleccionas un monstruo y/o un banco de preguntas, cuando llegas a EMPEZAR y seleccionas el botón, no hace nada.
Esto es porque no se ha seleccionado ni monstruo o un banco de preguntas, pero no te muestra un mensaje de excepción ni nada, con lo que no sabes qué ocurre.

**Comment by climentjoan** [comment]
Resuelto en la 1.25 misma.
