### ISSUE TITLE
Configuración Habilidades

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#29]
Al dejar como No disponibles las habilidades, accediendo como alumno, siguen apareciendo los 4 + para poder adquirir habilidades.

**Comment by climentjoan** [comment]
Cuando está desactivado, en la vista como alumno no se pueden comprar habilidades (no aparecen los cuadros), en la parte de docente, siempre salen para poder gestionarlas.
