### ISSUE TITLE
Comportamiento Muerte

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#32]
Si utilizo un comportamiento de -100, para que alguien muera, se le quitan los 100 HP, pero no se actualiza su imagen con el esqueleto. Se debe refrescar la pantalla para que tenga efecto.

**Comment by climentjoan** [comment]
Arreglado en la 1.41 y actualizado el personaje cuando muere (en los muertos actuales se mantiene el antiguo)
