### ISSUE TITLE
Literal no traducido

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#34]
Al acceder a:
Estudiantes - Área del estudiante - Registro - Cursor sobre el icono de la "i" cuando has "matado" al alumno, se muestra el literal: "students.log_null"

![image](https://user-images.githubusercontent.com/4247635/106893789-550b8500-66ee-11eb-918d-e5a7e8b4d2b0.png)

**Comment by climentjoan** [comment]
En los log_null no debería aparecer mensaje, no sé si se ha arreglado, lo puedes mirar?
