### ISSUE TITLE
Refrescar datos alumno al eliminar un registro

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#7]
En el apartado de alumno, cuando el Maestro elimina un registro (un comportamiento, monedas...) porque se ha equivocado, no se refresca el espacio del alumno. Tienes que refrescar la página.

Google Chrome
Versión 86.0.4240.75 (Build oficial) (64 bits)

**Comment by climentjoan** [comment]
He intentado reproducirlo y al eliminar tanto de comportamientos como del registro, automáticamente se refresca la página.

¿Aparece alguna cosa en la consola?

**Comment by ignaciosalazarcalle** [comment]
Ahora parece que funciona bien. Sin errores.
