### ISSUE TITLE
Insiginias - Personalizadas

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [climentjoan/fantasyclass#9]
Hola, 

¿Hay posibilidad de poder subir imágenes propias para la creación de las insiginias?

Un saludo,

**Comment by climentjoan** [comment]
Está previsto para un futuro.

Saludos!

**Comment by climentjoan** [comment]
Ya implementado

**Comment by ignaciosalazarcalle** [comment]
Genial!! Gracias.
